### ISSUE TITLE
Apotheotic Gems don't load and tooltip error when gates when you press shift over them

### ISSUE THREAD

**Issue by SpinoFTW** [Bryce792/ApotheoticAdditions#19]
here is the log for both of these https://mclo.gs/hx3m0lu and part 2 is https://mclo.gs/kzMZTir

**Comment by Bryce792** [comment]
The Apotheotic Additions Jewels appears to be due to Irons Spell books recently receiving an update converting spellbooks into curio slot items, so instead of it using the slot "spellbook" it now uses "curios:spellbook", for now, avoid attempting to reforge or obtain any spellbooks with rarities from apotheotic additions, (Artifact or higher) as it will most likely crash until I reupdate it.

As for the gateways compat, it appears to be triggered when Apotheosis Bosses are loaded into gates. To counter, in the same update, i can rebalance it to have the bosses intended stats, but in a normal form.
